### ISSUE TITLE
Web-IDE Project 진행 현황

### ISSUE THREAD

**Issue by jeeyn** [jeeyn/mentoring#1]
@jongfeel
멘토님, Web IDE 프로젝트 진행 현황 공유드리고, 몇 가지 질문 남깁니다.

### 1. [아키텍쳐 구성도](https://app.diagrams.net/#G1aGPW2lnm7l9hfi_k6GJGSO7HyMnfRL0z)
아키텍쳐 구성도는 이전에 보여드렸던 다른 팀의 구성도를 참고해서 그렸고,
GitHub Actions를 활용한 자동 배포 부분을 추가했습니다.

### 2. [시퀀스 다이어그램](https://excalidraw.com/#room=28ab430b4fed61536894,2TmGHQgwaQCju-KaqDgvvA)
코드 편집기 부분의 시퀀스 다이어그램을 작성하고 있습니다.
프로젝트 생성 / 조회 / 실행 및 저장 / 삭제를 나누어서 그릴 예정인데, 우선 생성과 조회를 먼저 작업했습니다.
(AWS 서비스들과 Docker는 사용한 경험이 적은데 이해하면서 진행해야 하니 꽤 어렵네요..🥲)
시퀀스 다이어그램을 다 그리는 대로 이 그림을 기반으로 API를 정의하고, 코드 작업할 예정입니다.
현재까지 그린 것에 오류가 없을 지 검토받고 싶습니다.

### 3. UI 설계
이 부분이 가장 큰 고민인데요.
각 기능별 API 정의 하면서 동시에 UI 설계(= 퍼블리싱) 작업을 진행하고자 하는데,
팀원들이 모두 프론트엔드 개발 경험이 없다보니 상당한 난관이 예상됩니다.

그래서 이 부분은 최대한 공수를 줄이고 싶은데...,
나이브하게 모두 다 구현하기 보다
유용하게 사용할 수 있을만한 노코드 툴 등 프론트 구현을 위한 다른 좋은 대안(방법)이 있을지 질문드립니다.

**Comment by jongfeel** [comment]
1.
S3의 용도가 아마 front-end 파일 업로드하는 부분일 것 같은데
그렇다면 react 그림이 S3로 배포되는 모양으로 가야 할 수도 있습니다.
그리고 axios는 아키텍처 상에서 크게 중요한 부분이 아닐 수 있으므로 설계 내용에 추가하는 것도 좋습니다.
마지막으로 이정도 프로젝트라면 axios 말고 fetch를 사용해도 됩니다.
fetch는 브라우저에서 사용하는 함수이므로 별도 설치가 필요 없기도 합니다.

2.
시퀀스는 크게 문제될 건 없어 보입니다.
진행하다가 순서가 변경되어야 한다는 걸 발견하고 수정하게 된다면 그 때마다 시퀀스 다이어그램 업데이트를 해 주세요.
나중에 프로젝트 종료 전에 문서 정리하다가 정리하기 귀찮음 폭탄을 맞을 수도 있습니다.

3.
프론트만 별도의 프로젝트로 세팅하고

- 웹 에디터 관련 오픈소스
- 채팅 관련 오픈소스

를 참고해서 그 소스 기반으로 만들어 나가는 것도 방법입니다.

현재는 아무도 프론트 관련된 개발을 하지 않았다면
react get started 스터디 부터 진행하고 component 개념을 익혔다면 그 다음에 다른 팀원과 나눠서 개발 진행할 수 있게 작업 영역을 나누면 됩니다.

중요한건 아직 안해봤으므로 **해보고 판단**하는게
앞으로 있을 난관의 시행착오를 줄이는 방법입니다.
