### ISSUE TITLE
개발 환경 구성

### ISSUE THREAD

**Issue by jeeyn** [jeeyn/mentoring#2]
@jongfeel
멘토님, 개발 환경 구성과 관련해서 질문드립니다.

어제까지 기획과 분석•설계 단계를 마무리하고,
오늘부터는 개발을 위한 환경 세팅을 준비하고 있습니다.

우선 1명이 GitHub에 환경 구성을 하고,
나머지 팀원들이 그걸 받아오는 순서로 공통 개발 환경 구성을 진행하려고 합니다.

그전에 각자 로컬에서 버전을 맞춰두어야 할 것 같은데, 아래의 항목들 정도만 체크하면 될까요?

**1. JDK**
java 21.0.1 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

**2. node.js**
v20.11.0

**3. npm**
10.2.4

혹시 환경 구성 시 더 고려해야 하는 부분이 있거나,
적용해 볼 수 있는 효율적인 방식이 있다면 조언 부탁드립니다!

**Comment by jongfeel** [comment]
그냥 하셔도 상관 없을 것 같습니다.

나중에 버전 업데이트 한다고 하면 서로 알려줘서 맞추는 정도만 해주면 좋습니다
