### ISSUE TITLE
원본 저장소 및 fork 저장소 브랜치 관리 전략

### ISSUE THREAD

**Issue by jeeyn** [jeeyn/mentoring#3]
@jongfeel
멘토님, 브랜치 관리와 관련하여 질문 드립니다.

지금 진행하고 있는 프로젝트에서는 코드 관리 과정을 아래와 같이 진행하고 있습니다.

1. 원본 저장소에서 각자 계정으로 fork
2. fork한 repo에서 기능별 브랜치(origin/feature) 생성 후 작업 및 push
3. pull request 후 원본 저장소 main 브랜치로  merge
4. fork 한 저장소 main 브랜치와 원본 저장소 sync 후 로컬로 pull
5. fork 한 저장소의 기존 브랜치(origin/feature) 삭제
6. 2~5번 반복

이 과정에서 궁금한 점이 몇 가지 있습니다.

Q1.
위의 2~3번 사이에 (원본 저장소에 pull request 하기 전에)
우선 origin/feature 브랜치와 origin/main 브랜치를 merge 한 후에 pull request를 작성하는게 나을지?

Q2.
현재는 원본 저장소에는 main 브랜치 하나에 pull request 작성 후 merge를 하고 있는데,
원본 저장소에서도 별도로 개인별 브랜치를 생성하고 해당 브랜치로 pull request - merge 한 후에
최종적으로 프로젝트 완료 단계에 main 브랜치 하나로 merge 하는 게 나을지?

기존에 저희가 진행하고 있는 방식이 괜찮은 방식인지,
일반적으로 현업에서 작업하시는 방식은 어떤지,
현업에서 사용하는 방식과는 어떤 차이가 있는지 알고 싶습니다.

**Comment by jongfeel** [comment]
1번 질문은 그렇게 하는 방식이 맞습니다.
만약 그렇게 안하면 계속 feature 브랜치의 내용이 누적되고 충돌이 일어나게 될 가능성이 높습니다.
항상 main branch에 merge가 일어나면 작업 중인 feature branch에 merge를 하고 pull request를 하면 좋습니다.

2번 질문의 대답은 상관 없다 입니다
2번 방식으로 한다면 원본을 fork한 repository는 원본 main branch sync용 repository가 되겠죠.

지윤님 팀 프로젝트의 기간과 구현 해야 하는 기능의 양을 비교해 봤을 때
checkout, commit, push, pull request, merge, pull로 이어지는 순환 사이클이 하루에도 몇 번, 많으면 수십번도 일어나야 하는 상황입니다.

제가 github flow 방식을 추천 드렸는데 그렇다면 2번 방식으로 전환하고
feature branch -> main branch로 merge 하는 작업을 빠르게 진행하면 좋을 것 같습니다.
추가로 GitHub issue에서 branch 생성하는 방식으로 하면 더욱 GitHub flow 방식의 순환 사이클 방식에 적합한 방식입니다.
